name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK 11 (or specify a different version if needed)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'  # Options: 'adopt', 'zulu', 'temurin', 'oracle'
        java-version: '11'     # Specify the Java version you want to use

    # Cache Maven dependencies to speed up subsequent builds
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Install dependencies and compile the application
    - name: Build with Maven
      run: mvn install

    # Run unit tests
    - name: Run tests
      run: mvn test

  
          
